### ISSUE TITLE
Any App brakes when theme is not passed to ThemeProvider

### ISSUE THREAD

**Issue by joaoprcosta** [Douro-ui/design-system#42]
**Describe the bug**
When not passing any theme as a prop of ThemeProvider, the application stops and returns an Uncaught Error.

<img width="1440" alt="Screenshot 2024-06-27 at 14 03 34" src="https://github.com/Douro-ui/design-system/assets/10466793/e6355d1e-3be7-4480-bf49-a494f7f03ac3">

The problem is on deepMerge util.
[
<img width="836" alt="Screenshot 2024-06-27 at 14 04 59" src="https://github.com/Douro-ui/design-system/assets/10466793/630a9f5f-caf6-40d8-89ce-f7839727a8a3">
](url)

**Comment by JuniorDiasOliveira** [comment]
It's fixed
